const state={token:sessionStorage.getItem('bpmPanelToken')||'',bootstrap:null,currentPage:'overview',currentLog:'backend',logTimer:null};
const pageTitles={overview:'运行总览',services:'服务管理',qqbot:'QQBot / NapCat',turtle:'海龟汤',storage:'对象存储',backend:'音乐后端配置',server:'游戏服务端',panel:'管理面板设置',logs:'实时日志'};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function headers(json=false){const h={};if(json)h['Content-Type']='application/json';if(state.token)h['X-Panel-Token']=state.token;return h;}
async function api(path,options={}){options.headers={...headers(Boolean(options.body)),...(options.headers||{})};const res=await fetch(path,options);let data={};try{data=await res.json()}catch{}if(res.status===401){showAuth();throw new Error('需要面板访问密钥')}if(!res.ok||data.ok===false)throw new Error(data.error||data.message||`HTTP ${res.status}`);return data;}
function toast(message,type='ok'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('#toastStack').append(el);setTimeout(()=>el.remove(),4500);}
function showAuth(){$('#authModal').classList.remove('hidden');setTimeout(()=>$('#authToken').focus(),30)}
function hideAuth(){$('#authModal').classList.add('hidden')}
function fmtBytes(n){n=Number(n||0);if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;if(n<1073741824)return`${(n/1048576).toFixed(1)} MB`;return`${(n/1073741824).toFixed(2)} GB`}
function valueOf(scope,key){return state.bootstrap?.settings?.[scope]?.[key]||{value:'',configured:false}}
function fieldHtml(field,scope){const current=valueOf(scope,field.key);const id=`field-${scope}-${field.key}`;let control='';if(field.type==='switch'){const on=String(current.value||field.default).toLowerCase();const checked=['1','true','yes','on'].includes(on);control=`<div class="switch-field"><input id="${id}" data-scope="${scope}" data-key="${field.key}" data-type="switch" value="${checked?'1':'0'}"><div class="switch ${checked?'on':''}" data-switch="${id}"></div><span class="switch-state">${checked?'已启用':'已关闭'}</span></div>`}else if(field.type==='secret'){control=`<div class="secret-wrap"><input id="${id}" type="password" data-scope="${scope}" data-key="${field.key}" data-type="secret" placeholder="${current.configured?'已配置，留空保持不变':'尚未配置'}" autocomplete="new-password"><button type="button" data-clear-secret="${id}">${current.configured?'清空':'未配置'}</button></div>${current.configured?'<span class="secret-configured">● 已在服务器本地配置</span>':''}`}else{control=`<input id="${id}" type="${field.type==='number'?'number':field.type==='url'?'text':'text'}" data-scope="${scope}" data-key="${field.key}" data-type="${field.type}" value="${escapeHtml(current.value||field.default||'')}" autocomplete="off">`}return`<div class="field"><label for="${id}"><span>${escapeHtml(field.label)}</span><code>${field.key}</code></label>${control}<p>${escapeHtml(field.help)}</p></div>`}
function renderForm(container,section,scope='env'){const el=$(container);if(!el)return;el.innerHTML=`<div class="form-section-head"><div><h3>${escapeHtml(section.title)}</h3><p>${escapeHtml(section.description||'配置将写入服务器本地文件。')}</p></div><span class="mini-note">保存后重启相关服务</span></div><div class="form-grid">${section.fields.map(f=>fieldHtml(f,scope)).join('')}</div>`}
function bindFormControls(){$$('[data-switch]').forEach(sw=>sw.onclick=()=>{const input=$(`#${sw.dataset.switch}`);const on=input.value!=='1';input.value=on?'1':'0';sw.classList.toggle('on',on);sw.nextElementSibling.textContent=on?'已启用':'已关闭'});$$('[data-clear-secret]').forEach(btn=>btn.onclick=()=>{const input=$(`#${btn.dataset.clearSecret}`);input.value='';input.dataset.clear='1';btn.textContent='将清空';btn.style.color='#ff7a90'})}
function renderForms(){const schema=state.bootstrap.schema;schema.env.forEach(section=>renderForm(`#form-${section.id}`,section,'env'));renderForm('#form-server',{title:'服务端核心配置',description:'保存到 myServerconfig.cfg。',fields:schema.server},'server');bindFormControls()}
function serviceRow(name,label,symbol,status){const text=status.running?(status.managed?`运行中 · PID ${status.pid}`:'已在面板外运行'):'未运行';return`<div class="service-row"><div class="service-symbol">${symbol}</div><div><b>${label}</b><small>${text}</small></div><span class="state-pill ${status.running?'online':''}">${status.running?'ONLINE':'OFFLINE'}</span></div>`}
function serviceCard(name,label,symbol,desc,status){return`<article class="service-card"><div class="service-top"><div class="big-symbol">${symbol}</div><div><span class="section-tag">${status.running?'RUNNING':'STOPPED'}</span><h3>${label}</h3></div></div><p class="service-description">${desc}<br>${status.external?'当前由面板外部启动，因此只读显示状态。':status.managed?`面板管理 PID：${status.pid}`:'可以由面板启动并收集日志。'}</p><div class="service-actions"><button class="start" data-service="${name}" data-action="start">启动</button><button data-service="${name}" data-action="restart">重启</button><button class="danger" data-service="${name}" data-action="stop">停止</button></div></article>`}
function checklistItem(ok,text){return`<div class="check-item"><span class="check-icon ${ok?'ok':''}">${ok?'✓':'!'}</span><span>${escapeHtml(text)}</span></div>`}
function renderStatus(s){const server=s.services.server,backend=s.services.backend,qq=s.qqbot||{},storage=s.storage||{};$('#metricServer').textContent=server.running?'运行中':'未运行';$('#metricServerSub').textContent=server.external?'外部进程':server.pid?`PID ${server.pid}`:'等待启动';$('#metricBackend').textContent=s.backend.online?'在线':'离线';$('#metricBackendSub').textContent=s.backend.online?'健康检查通过':(s.backend.error||'无法连接').slice(0,30);$('#metricQq').textContent=qq.connected?'已连接':qq.enabled?'等待连接':'未启用';$('#metricQqSub').textContent=qq.last_error||qq.websocket_url||'NapCat OneBot';$('#metricStorage').textContent=storage.configured?'已配置':'未配置';$('#metricStorageSub').textContent=storage.bucket||storage.endpoint||'S3 compatible';$('#overviewServices').innerHTML=serviceRow('server','DDNet 游戏服务端','D',server)+serviceRow('backend','Python 音乐后端','♫',backend);$('#serviceCards').innerHTML=serviceCard('backend','Python 音乐后端','♫','负责音乐搜索、下载、地图缝合、QQBot 与小游戏数据接口。',backend)+serviceCard('server','DDNet 游戏服务端','D','承载玩家、地图、点歌队列和休闲玩法。',server);const r=s.runtime||{},t=s.turtle||{};$('#checklist').innerHTML=[checklistItem(Boolean(r.ffmpeg),'FFmpeg 可用'),checklistItem(Boolean(r.map_patcher),'music_map_patcher 路径已解析'),checklistItem(Boolean(r.server_exe),'DDNet-Server.exe 可用'),checklistItem(Boolean(t.exists&&!t.error),`海龟汤题库 ${t.cases||0} 道`),checklistItem(Boolean(r.map),'默认地图 a.map 已配置'),checklistItem(Boolean(r.font),'中文字体资源已配置')].join('');const usage=s.usage||{};$('#usageGrid').innerHTML=`<div class="usage-box"><small>音乐文件</small><b>${usage.music?.files||0}</b><span>${fmtBytes(usage.music?.bytes)} · ${escapeHtml(usage.music?.path||'')}</span></div><div class="usage-box"><small>候选地图</small><b>${usage.prepared_maps?.files||0}</b><span>${fmtBytes(usage.prepared_maps?.bytes)} · ${escapeHtml(usage.prepared_maps?.path||'')}</span></div>`;const any=s.backend.online||server.running;$('#globalDot').classList.toggle('online',any);$('#globalState').textContent=any?'节点在线':'节点待启动';$('#lastUpdate').textContent=`更新于 ${new Date((s.time||Date.now()/1000)*1000).toLocaleTimeString()}`;bindServiceButtons()}
function bindServiceButtons(){$$('[data-service]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{const data=await api(`/api/service/${btn.dataset.service}/${btn.dataset.action}`,{method:'POST'});toast(data.message);await refreshStatus()}catch(e){toast(e.message,'error')}finally{btn.disabled=false}})}
async function runCheck(name){toast('正在执行检查…');try{const data=await api(`/api/check/${name}`,{method:'POST'});toast(data.message,data.ok?'ok':'error')}catch(e){toast(e.message,'error')}}
async function refreshStatus(){try{const data=await api('/api/status');renderStatus(data.status)}catch(e){$('#globalState').textContent='面板连接失败';toast(e.message,'error')}}
async function saveAll(){const payload={env:{},server:{},clearSecrets:[]};$$('[data-scope][data-key]').forEach(input=>{const scope=input.dataset.scope,key=input.dataset.key;if(input.dataset.type==='secret'&&!input.value&&!input.dataset.clear)return;payload[scope][key]=input.value;if(input.dataset.clear)payload.clearSecrets.push(key)});try{const data=await api('/api/settings',{method:'POST',body:JSON.stringify(payload)});toast(data.message);await loadBootstrap()}catch(e){toast(e.message,'error')}}
async function loadLogs(){try{const data=await api(`/api/logs/${state.currentLog}?lines=350`);const pre=$('#logOutput');const nearBottom=pre.scrollHeight-pre.scrollTop-pre.clientHeight<80;pre.textContent=data.content;if(nearBottom)pre.scrollTop=pre.scrollHeight}catch(e){$('#logOutput').textContent=e.message}}
function showPage(name){state.currentPage=name;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===name));$('#pageTitle').textContent=pageTitles[name]||name;if(name==='logs')loadLogs()}
async function loadBootstrap(){try{const data=await api('/api/bootstrap');state.bootstrap=data;renderForms();renderStatus(data.status);hideAuth()}catch(e){if(!$('#authModal').classList.contains('hidden'))return;toast(e.message,'error')}}
function initEvents(){$$('.nav-item').forEach(n=>n.onclick=()=>showPage(n.dataset.page));$('#refreshButton').onclick=refreshStatus;$('#saveAllButton').onclick=saveAll;$$('[data-check]').forEach(b=>b.onclick=()=>runCheck(b.dataset.check));$$('[data-log]').forEach(b=>b.onclick=()=>{state.currentLog=b.dataset.log;$$('[data-log]').forEach(x=>x.classList.toggle('active',x===b));loadLogs()});$('#refreshLogs').onclick=loadLogs;$('#authSubmit').onclick=()=>{state.token=$('#authToken').value.trim();sessionStorage.setItem('bpmPanelToken',state.token);loadBootstrap()};$('#authToken').onkeydown=e=>{if(e.key==='Enter')$('#authSubmit').click()}}
async function boot(){initEvents();await loadBootstrap();setInterval(refreshStatus,6000);state.logTimer=setInterval(()=>{if(state.currentPage==='logs'&&$('#autoLogs').checked)loadLogs()},2500)}
boot();
